---
workspace:
  base: /drone
  path: src

pipeline:
  lint-shell:
    image: sevoid/linter:latest
    group: lint
    commands:
      - ./.ci/lint-shell.sh

  lint-yaml:
    image: sevoid/linter:latest
    group: lint
    commands:
      - ./.ci/lint-yaml.sh

  lint-dockerfile:
    image: sevoid/linter:latest
    group: lint
    commands:
      - ./.ci/lint-dockerfile.sh

  docker-build-and-push:
    image: plugins/docker:17
    secrets:
      - docker_username
      - docker_password
    repo: sevoid/linter
    tags:
      - 'latest'
    when:
      branch:
        - build-*

branches:
  exclude: [ master ]

# vim:set syntax=yaml ts=2 sw=2 et:
